DBwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cardSearch.views import SearchResult
from django.contrib.auth import views as auth_views
from users.forms import CustomAuthenticationForm
from users.views import custom_logout_view

urlpatterns = [
    path('', include("homepage.urls")),
    path("search/", include("baseTemplates.urls")),
    path('cards/', include("cardSearch.urls")),
    # Cambiamos el form del login para poder usar clases
    path('user/login/', auth_views.LoginView.as_view(
        template_name = 'registration/login.html',
        authentication_form = CustomAuthenticationForm
    ), name="login"),
    path('user/', include("users.urls")),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('django_registration.backends.one_step.urls')),
    path('admin/', admin.site.urls),
    path('decks/', include("deckbuilder.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cardSearch/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('advanced/', views.advanced_search, name="advanced-search"),
    path("set/<str:set_id>", views.specific_set_cards, name="specific_set_cards"),
    path("<set_id>/<int:card_id>", views.specific_card_info, name="specific_card_info"),
    path("<int:card_id>", views.specific_card_info, name="generic_card_info"),
    path('search/', views.SearchResult.as_view()),
    path('search/<str:user_query>', views.SearchResult.as_view(), name='search-cards-view'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('logout/', views.custom_logout_view, name='logout'),
]

RoGDB/models.py
from django.db import models
from multiselectfield import MultiSelectField
import re
import copy

# TODO: Pensar bien que va a pasar al borrar con las FK !!!

class CardSet(models.Model):
    set_name = models.CharField("Nombre", max_length=200)
    set_code = models.CharField("Código", max_length=200, unique=True)
    set_type = models.CharField("Tipo", max_length=200, default="")
    released_date = models.DateField("Fecha de lanzamiento")
    total_cards = models.IntegerField("Cantidad de cartas", default=0)
    is_visible = models.BooleanField("¿Es visible?", default=False)

    class Meta:
        ordering = ['-released_date']
        verbose_name = "Set"
        verbose_name_plural = "Expansiones"

    def __str__(self):
        return self.set_name
    
    def get_list_of_sets():
        set_list = CardSet.objects.all().order_by('-released_date')
        set_list = set_list.exclude(is_visible=False)
        return_list = [("","---")]
        for card_set in set_list:
            return_list.append((card_set.set_code,card_set.set_name))
        return return_list


class Format(models.Model):
    format_name = models.CharField("Nombre", max_length=200)
    format_desc = models.TextField("Descripción", default="")
    card_id = models.ManyToManyField("Card", through="FormatFollows" ,verbose_name="Carta")

    class Meta:
        verbose_name = "Formato"
        verbose_name_plural = "Formatos"

    def __str__(self):
        return self.format_name
    
    def get_list_of_formats():
        # Ver como ordenar la lista
        format_list = Format.objects.all()
        return_list = [("","---")]
        for format in format_list:
            return_list.append((format.format_name,format.format_name))
        return return_list
    
    def check_deck_legality(format, deck_list):
        
        # Devuelve si el deck es legal en el formato o no.
        # Este juego tiene una regla importante, la cantidad de cartas está determinada por su rareza. Entonces:
        # - Común: 4 copias
        # - Rara: 3 copias
        # - Épica: 2 copias
        # - Legendaria: 1 copia
        # Ademas de una lista de cartas prohibidas.

        # Primero agregamos la cant de cartas en el side junto con el main, asi revisamos todo junto
        main_deck_size = 0
        side_deck_size = 0

        full_deck_copy = copy.deepcopy(deck_list["main"])

        for side_card in deck_list["side"]:
            found = False
            for main_card in full_deck_copy:
                if main_card["id"] == side_card["id"]:
                    main_quantity = int(main_card["quantity"])
                    main_card["quantity"] = str(main_quantity + int(side_card["quantity"]))
                    found = True
            if not found:
                full_deck_copy.append(copy.deepcopy(side_card))
        for card in full_deck_copy:
            # Ver de poner una excepción para los sigilos
            full_info_card = Card.get_card_by_id(card["id"])
            match full_info_card.rarity:
                case 1:
                    if int(card["quantity"])>4:
                        return False
                case 2:
                    if int(card["quantity"])>3:
                        return False
                case 3:
                    if int(card["quantity"])>2:
                        return False
                case 4:
                    if int(card["quantity"])>1:
                        return False
            if Card.check_if_banned(format, card["id"]):
                return False
        for card in deck_list["main"]:
            main_deck_size += int(card["quantity"])
        for card in deck_list["side"]:
            side_deck_size += int(card["quantity"])
        
        # Luego ver de definir el tamaño del mazo según el formato
        if main_deck_size == 40 and side_deck_size == 10:
            return True
        else:
            return False


class Card(models.Model):

    RARITY=[
        (0, "Token"),
        (1, "Común"),
        (2, "Rara"),
        (3, "Épica"),
        (4, "Legendaria"),
    ]

    FACTIONS = [
        ("J", "Jupiter"),
        ("M", "Marte"),
        ("N", "Neptuno"),
        ("P", "Pluton"),
        ("S", "Saturno"),
        ("T", "Tierra"),
    ]

    card_name = models.CharField("Nombre", max_length=200)
    faction = MultiSelectField("Facción", choices=FACTIONS, blank=True)
    card_type = models.CharField("Tipo", max_length=200)
    cost = models.CharField("Coste", default="", max_length=30)
    converted_cost = models.IntegerField("Coste convertido", default=0)
    rarity = models.IntegerField("Rareza", choices=RARITY)
    attack = models.IntegerField("Ataque", blank=True, null=True)
    health = models.IntegerField("Vida", blank=True, null=True)
    text_box = models.TextField("Habilidad", blank=True, default="")
    rules_explanation = models.TextField("Explicación de reglas", blank=True, default="")
    related_cards = models.ManyToManyField('self', blank=True, verbose_name="Cartas relacionadas")
    card_legality = models.ManyToManyField(Format, through='FormatFollows', blank=True, verbose_name="Legalidad")

    class Meta:
        ordering = ['card_name']
        verbose_name = "Carta"
        verbose_name_plural = "Cartas"

    def __str__(self):
        return self.card_name
    
    def get_card_by_id(card_id):
        return Card.objects.get(pk=card_id)
    
    def check_if_banned(format,card):
        card_legality = FormatFollows.objects.get(card_id=card, format_id__format_name__iexact=format)
        if card_legality:
            if card_legality.legality == "B":
                return True
            else:
                return False
        else:
            return None # TODO: Ver si programar un código de error
    
    
    def save(self, *args, **kwargs):
        # Calculamos el coste convertido en base al coste antes de guardar
        if not self.cost:
            cost = 0
        else:
            cost = 0
            # Separar el número inicial si existe
            match = re.match(r'^(\d+)', self.cost)
            if match:
                cost += int(match.group(1))
                cost_str = self.cost[match.end():]  # quitar el número inicial
            else:
                cost_str = self.cost
            # Sumar 1 por cada letra (P, M, etc.)
            for char in cost_str:
                if char.isalpha():
                    cost += 1
        self.converted_cost = cost

        # Cambiamos el ataque y vida a -1 si es una carta sin ataque/vida
        if not self.attack:
            self.attack = -1
        if not self.health:
            self.health = -1
        
        super().save(*args, **kwargs)

    @staticmethod
    def get_list_of_factions():
        return Card.FACTIONS

class FormatFollows (models.Model):

    LEGALITY = [
        ("L", "Legal"),
        ("B", "Prohibida"),
        ("N", "No legal"),
    ]

    card_id = models.ForeignKey(Card, on_delete=models.DO_NOTHING, verbose_name="Carta")
    format_id = models.ForeignKey(Format, on_delete=models.CASCADE, verbose_name="Formato")
    legality = models.CharField(max_length=3, choices=LEGALITY, default="L", verbose_name="Legalidad")

    class Meta:
        verbose_name = "Legalidad de carta"
        verbose_name_plural = "Legalidades de cartas"

    def __str__(self):
        return self.format_id.format_name + " - " + self.get_legality_display() + " (" + self.card_id.card_name + ")"


class CardVersion(models.Model):
    card_id = models.ForeignKey(Card, on_delete=models.CASCADE, verbose_name="Carta")
    set_id = models.ForeignKey(CardSet, on_delete=models.RESTRICT, verbose_name="Set")
    serial_number = models.IntegerField("Código de carta")
    is_skin = models.BooleanField(default=False, verbose_name="¿Es una skin?")
    card_art = models.ImageField("Arte", blank=True, upload_to="media/card_art")
    artist = models.CharField("Artista", max_length=200)
    flavor_text = models.TextField("Texto de ambientación (Flavor)", blank=True, default="")
    label = models.CharField("Etiqueta", blank=True, max_length=200, default="")
    last_print = models.BooleanField("Última impresión", default=True)

    class Meta:
        get_latest_by = "-pk"
        verbose_name = "Versión de carta"
        verbose_name_plural = "Versiones de cartas"

    # Esto revisa si la carta que se está subiendo es más actual que el resto.
    # De ser así, pone esa carta como la reprensentativa de la carta. En caso contrario deja la que estaba antes.
    def save(self, **kwargs):
        other_versions = CardVersion.objects.filter(card_id=self.card_id)
        for version in other_versions:
            if version.set_id.released_date > self.set_id.released_date:
                self.last_print = False
                break
            else:
                version.last_print = False
        super().save(**kwargs)

    def __str__(self):
        return self.set_id.set_code  + " - " + self.card_id.card_name
    
    # Hacer diferentes querys para la busqueda. Ver como pasar esos parametros.
    # Creo que deberia tener una funcion general que revise el string y va llamando lo que necesita

    def get_last_version(user_query):
        # Crear una funcion para reparar la db en caso de error
        try:
            return CardVersion.objects.get(card_id=user_query, last_print=True)
        except CardVersion.MultipleObjectsReturned:
            pass
    
    def get_all_cards_from_set_code(user_query):
        return CardVersion.objects.filter(set_id__set_code=user_query, set_id__is_visible=True)
    
    def get_all_versions_of_a_card(user_query):
        return CardVersion.objects.filter(card_id=user_query, set_id__is_visible=True).order_by('-set_id__released_date')
    
    def get_card_by_name(user_query, get=True):
        if get:
            return CardVersion.objects.get(card_id__card_name__icontains=user_query, last_print=True)
        else:

cardSearch/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.db.models import Q
from RoGDB.models import CardVersion, Card
from RoGDB.forms import AdvancerSearchForm


def advanced_search(request):
    if request.method == "POST":
        advanced_form = AdvancerSearchForm(request.POST)
        if advanced_form.is_valid():
            query_string = CardVersion.construct_string(advanced_form.cleaned_data)
            return HttpResponseRedirect(f'/cards/search/{query_string}')
    else:
        advanced_form = AdvancerSearchForm()
    return render (request, "cardSearch/advanced.html", {'form': advanced_form})


def specific_card_info(request, card_id, set_id=False):
    try:
        if set_id:
            card = CardVersion.get_specific_card(card_id,set_id)
        else:
            card = CardVersion.get_last_version(card_id)
        other_prints = CardVersion.get_all_versions_of_a_card(card.card_id)
        related_cards = card.card_id.related_cards.all()
        related_cards_info = []
        for related_card in related_cards:
            related_cards_info.append(CardVersion.get_last_version(related_card.pk))
        context = { 
            'requestedcard': card,
            'otherprints': other_prints,
            'relatedcards': related_cards_info,
        }
        return render (request, "cardSearch/card.html", context)
    except CardVersion.DoesNotExist:
        raise Http404 ("Card not found")


def specific_set_cards(request, set_id):
    return HttpResponseRedirect(f"/cards/search/set:{set_id}")


class SearchResult(ListView):
    model = CardVersion
    paginate_by = 30
    template_name = "cardSearch/search.html"
    context_object_name = "card_list"
    ordering = ['card_id__card_name']

    # Actualizamos el contexto para mostrar el campo de ordenación y la dirección correctos en el template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        sort_by = self.request.GET.get('sort_by', 'card_id__card_name')
        order = self.request.GET.get('order', 'des')

        context['current_sort_by'] = sort_by
        context['current_order'] = order

        # Mapeo de campos para mostrar texto legible
        field_labels = {
            'card_id__card_name': 'Nombre',
            'card_id__faction': 'Facciones',
            'card_id__rarity': 'Rareza',
            'card_id__converted_cost': 'Coste total',
            'card_id__attack': 'Ataque',
            'card_id__health': 'Salud',
            'card_id__release_date': 'Fecha de impresión',
        }

        context['sort_by_label'] = field_labels.get(sort_by, 'Nombre')
        context['order_label'] = 'Ascendente' if order == 'asc' else 'Descendente'
        context['order_icon'] = 'bi-arrow-up' if order == 'asc' else 'bi-arrow-down'

        return context

    def get_queryset(self):
        try:
            user_query = self.kwargs['user_query']
            queryset = CardVersion.evaluate_string(user_query)
        except KeyError:
            # TODO: Programar un aviso de que no se encontró ningun resultado
            queryset = CardVersion.get_all_cards()
        
        # Ordenamos según el campo y dirección de ordenación seleccionados. Por defecto, ordena por nombre de carta de forma ascendente
        sort_by = self.request.GET.get('sort_by', 'card_id__card_name')
        order = self.request.GET.get('order', 'asc')

        # Como reemplazamos el get_queryset, hay que llamar a get_ordering manualmente
        ordering = f"-{sort_by}" if order == 'des' else sort_by
        return queryset.order_by(ordering)
    
    # Si el resultado de la busqueda devuelve solo una carta, redirecciona directamente a la info de esa carta
    def render_to_response(self, context, **response_kwargs):
        if len(self.object_list) == 1:
            return redirect(f"/cards/{self.object_list[0].card_id_id}")
        return super().render_to_response(context, **response_kwargs)
     

cardSearch/templates/cardSearch/advanced.html
{% extends "baseTemplates/base.html" %}

{% block title %}RoG - Buscador Avanzado{% endblock %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static "cardSearch/style.css" %}">

  <div class="container py-5">
    <h2 class="text-center mb-4 text-white">Buscador Avanzado</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-md-10 col-lg-6">
        <form method="POST" role="search" class="d-flex flex-column align-items-center gap-3">
          {% csrf_token %}

          <div class="form-group w-100 row">
            <label for="{{ form.card_name.id_for_label }}" class="form-label">{{ form.card_name.label }}</label>
            {{ form.card_name }}
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.text_box.id_for_label }}" class="form-label">{{ form.text_box.label }}</label>
            {{ form.text_box }}
            <div class="form-text text-white fst-italic">Ingrese texto de la caja de habilidades. El orden no importa.</div>
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.card_type.id_for_label }}" class="form-label">{{ form.card_type.label }}</label>
            {{ form.card_type }}
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.faction.id_for_label }}" class="form-label">{{ form.faction.label }}</label>
            {{ form.faction }}
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.rarity.id_for_label }}" class="form-label">{{ form.rarity.label }}</label>
            {{ form.rarity }}
          </div>

          <!-- Agregar un formateador para ingresar iconos. Puede que separar el coste génerico del de facción sea una buena idea -->
          <div class="form-group w-100 row">
            <label for="{{ form.cost.id_for_label }}" class="form-label">{{ form.cost.label }}</label>
            {{ form.cost }}
            <div class="form-text text-white fst-italic">Encuentre cartas con este coste exacto.</div>
          </div>

          <div class="row w-100 align-items-center">
            <label for="{{ form.converted_cost.id_for_label }}" class="form-label">{{ form.converted_cost.label }}</label>
            <div class="form-group col-6">
              {{ form.cc_operator }}
            </div>
            <div class="form-group col-6">
              {{ form.converted_cost }}
            </div>
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.attack.id_for_label }}" class="form-label">{{ form.attack.label }}</label>
            <div class="form-group col-6">
              {{ form.a_operator }}
            </div>
            <div class="form-group col-6">
              {{ form.attack }}
            </div>
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.health.id_for_label }}" class="form-label">{{ form.health.label }}</label>
            <div class="form-group col-6">
              {{ form.h_operator }}
            </div>
            <div class="form-group col-6">
              {{ form.health }}
            </div>
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.set_dropdown.id_for_label }}" class="form-label">{{ form.set_dropdown.label }}</label>
            {{ form.set_dropdown }}
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.legality.id_for_label }}" class="form-label">{{ form.legality.label }}</label>
            {{ form.legality }}
          </div>

          <div class="form-group w-100 row">
            <label for="{{ form.format.id_for_label }}" class="form-label">{{ form.format.label }}</label>
            {{ form.format }}
          </div>

          <div class="col-12 d-flex justify-content-center gap-5 mt-3">
            <button type="reset" class="btn btn-secondary">
              Limpiar <i class="bi bi-x-circle"></i>
            </button>
            <button type="submit" class="btn btn-primary">
              Buscar <i class="bi bi-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

cardSearch/templates/cardSearch/card.html
{% extends "baseTemplates/base.html" %}

{% block title %}RoG - {{ requestedcard.card_id.card_name }}{% endblock %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static "cardSearch/style.css" %}">
  <div class="container card-info-container d-flex flex-column flex-xl-row align-items-start pb-3">

      <!-- Imagen de la carta -->
      <div class="card-illustration mb-3">
        <img src="{{ requestedcard.card_art.url }}" class="img-fluid">
      </div>

      <!-- Info de la carta -->
      <div class="card-info pe-2">
        <ul class="list-group list-group-flush bg-transparent border border-light-subtle text-white">
          <li class="list-group-item bg-transparent">
            <div class="d-flex align-items-center">
              <h5 class="mb-0 me-2"><b>{{ requestedcard.card_id.card_name }}</b></h5>
              <div id="card-cost">{{requestedcard.card_id.cost}}</div>
            </div>
          </li>
          <li class="list-group-item bg-transparent"><span class="rarity-dot" rarity-value={{requestedcard.card_id.rarity}}></span> {{ requestedcard.card_id.get_rarity_display }}</li>
          <li class="list-group-item bg-transparent">{{requestedcard.card_id.card_type}}</li>
          <li class="list-group-item bg-transparent">{{requestedcard.card_id.text_box}}</li>
          {% if requestedcard.card_id.attack > 0 %} <!-- Revisar esto, si la carta no tiene ataque no va a aparecer este dato -->
            <li class="list-group-item bg-transparent">{{requestedcard.card_id.attack}}/{{requestedcard.card_id.health}}</li>
          {% endif %}
          <li class="list-group-item bg-transparent"><em>Ilustrado por: <a href="/cards/search/artist={{requestedcard.artist}}" class="link-body-emphasis link-underline-opacity-0 link-underline-opacity-75-hover">{{requestedcard.artist}}</a></em></li>
        </ul>
        <!--Poner las legalidades acá-->
      </div>

      <!-- Sets e impresiones -->
      <div class="card-set align-self-top">
        <a class="btn btn-primary set-button text-start" href="/cards/set/{{ requestedcard.set_id.set_code }}">
          <h5 class="mb-0">{{requestedcard.set_id.set_name}} ({{ requestedcard.set_id.set_code }})</h5>
          #{{ requestedcard.serial_number }}
        </a>
        <div class="prints">
          <div class="prints-title">
            <p>IMPRESIONES</p>
          </div>
          <ul class="list-group z-0">
          {% for print in otherprints %}
              <a class="show-card-image list-group-item list-group-item-action {% if print.pk == requestedcard.pk %}active{% endif %}" href="/cards/{{print.set_id.set_code}}/{{print.serial_number}}" data-card-art="/media/{{print.card_art}}">{{print.set_id.set_name}}</a>
          {% endfor %}
          </ul>
        </div>
      {% if requestedcard.card_id.related_cards.all %}
        <div class="related-cards">
          <p>CARTAS RELACIONADAS</p>
          <ul class="list-group z-0">
          {% for related_card in relatedcards %}
            <!--Arreglar el link del arte-->
            <a class="show-card-image list-group-item list-group-item-action" href="/cards/{{ related_card.pk }}" data-card-art="/media/{{related_card.card_art}}">{{ related_card.card_id.card_name }}</a>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
      </div>
    </div>

  <!-- Esta es una imagen que se va a mostrar cuando se ponga el mouse sobre una carta en la lista -->
  <div class="img-on-hover z-2">
    <img src="#" class="img-hover"></img>
  </div>
  <script src={% static "cardSearch/showImageWhenHovering.js" %}></script>
  <script src={% static "cardSearch/convertCardCost.js" %}></script>
{% endblock %}

cardSearch/templates/cardSearch/search.html
{% extends "baseTemplates/base.html" %}

{% block title %}RoG - Buscar cartas{% endblock %}

{% block content %}
  {% load static %}
  <!--FIXME Ver porque no funciona ir a mis mazos desde este template-->
  <link rel="stylesheet" href="{% static "cardSearch/style.css" %}">
  <div class="search-result pb-5">
    <form method="POST" role="search">
      <div class="search-options pb-3 gap-3 d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-md-between text-center text-md-start">
        {% csrf_token %}
        <div class = "d-flex gap-2">
          <div class="dropdown">
            <button 
              id="sort-field-button"
              class="btn btn-dark dropdown-toggle w-100 w-md-auto btn-sm" 
              type="button" 
              data-bs-toggle="dropdown" 
              aria-expanded="false"
              data-query={{current_sort_by}}>
              {{ sort_by_label }}
            </button>
            <ul class="dropdown-menu" >
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__card_name' %}active{% endif %}" href="#" data-query="card_id__card_name">Nombre</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__faction' %}active{% endif %}" href="#" data-query="card_id__faction">Facciones</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__rarity' %}active{% endif %}" href="#" data-query="card_id__rarity">Rareza</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__converted_cost' %}active{% endif %}" href="#" data-query="card_id__converted_cost">Coste total</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__attack' %}active{% endif %}" href="#" data-query="card_id__attack">Ataque</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'card_id__health' %}active{% endif %}" href="#" data-query="card_id__health">Salud</a></li>
              <li><a class="dropdown-item {% if current_sort_by == 'todo' %}active{% endif %}" href="#" data-query="card_id__card_name">Fecha de impresión</a></li> <!-- Ver como poner esto -->
            </ul>
          </div>
          <div class="dropdown">
            <button 
              id="sort-direction-button"
              class="btn btn-dark dropdown-toggle w-100 w-md-auto btn-sm" 
              type="button" 
              data-bs-toggle="dropdown" 
              aria-expanded="false"
              data-query={{current_order}}>
              <i class="bi {{ order_icon }}"></i> {{ order_label }}
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item {% if current_order == 'asc' %}active{% endif %}" href="#" data-query="asc"><i class="bi bi-arrow-up"></i> Ascendente</a></li>
              <li><a class="dropdown-item {% if current_order == 'des' %}active{% endif %}" href="#" data-query="des"><i class="bi bi-arrow-down"></i> Descendente</a></li>
            </ul>
          </div>
        </div>
        <div class = "align-items-right">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1" class="btn btn-dark btn-sm"><b><i class="bi bi-arrow-bar-left"></i></b></a>
              <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-dark btn-sm"><i class="bi bi-arrow-left-short"></i> Anterior</a>
            {% else %}
            <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-bar-left"></i></a>
            <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-left-short"></i> Anterior</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" class="btn btn-dark btn-sm">Siguiente <i class="bi bi-arrow-right-short"></i></a>
              <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-dark btn-sm"><i class="bi bi-arrow-bar-right"></i></a>
            {% else %}
              <a class="btn btn-dark disabled btn-sm">Siguiente <i class="bi bi-arrow-right-short"></i></a>
              <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-bar-right"></i></a>
            {% endif %}
          </span>
        </div>
      </div>
    </form>
    <!-- La idea es mostrar las cartas en paginas, de forma estatica. -->
    <div class="search-info text-center text-md-start">
      <!-- Esta info es para testear, cambiar por lo que corresponda luego -->
      <p class="fs-6">Se encontraron {{ page_obj.paginator.count }} cartas</p>
    </div>
    <!-- Acá está el loop que carga el arte de las cartas, y les asigna una url. -->
    <div class="card-list">
      {% for card in card_list %}
          <div class="individual-card">
            <a href="/cards/{{ card.set_id.set_code }}/{{ card.serial_number }}">
              <img src="{{ card.card_art.url }}"  alt={{"card.card_id.card_name"}}>
            </a>
          </div>
      {% endfor %}
    </div>
    <div class="bottom-control-row">
      <div class = "control-left-side">
      </div>
      <div class = "control-right-side">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-dark btn-sm"><b><i class="bi bi-arrow-bar-left"></i></b></a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-dark btn-sm"><i class="bi bi-arrow-left-short"></i> Anterior</a>
          {% else %}
          <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-bar-left"></i></a>
          <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-left-short"></i> Anterior</a>
          {% endif %}
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-dark btn-sm">Siguiente <i class="bi bi-arrow-right-short"></i></a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-dark btn-sm"><i class="bi bi-arrow-bar-right"></i></a>
          {% else %}
            <a class="btn btn-dark disabled btn-sm">Siguiente <i class="bi bi-arrow-right-short"></i></a>
            <a class="btn btn-dark disabled btn-sm"><i class="bi bi-arrow-bar-right"></i></a>
          {% endif %}
        </span>
      </div>
    </div>
  </div>
  <script src={% static "cardSearch/dropdownLogic.js" %}></script>
{% endblock %}